config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :backgrounds
  resources :references
  resources :interviews
  resources :assessments
  resources :participants
  resources :projects
  resources :expenses
  resources :businesses
  resources :resumes

  resources :contributions do
    member do
      get 'index_individual'
    end
  end

  resources :offers

  resources :identities

  get 'home/dsds'
  get 'home/news'
  get 'home/about'
  get 'home/help'
  get 'home/letter'
  get 'home/letter_short'
  root 'home#index'

  devise_for :users

end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy]

  # GET /businesses
  # GET /businesses.json
  def index

    if current_user.level > 19
      @businesses = Business.all
    else
      redirect_to root_url, notice: 'Access Denied! Business6342'
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show

    #show has account and password, only accessable with raw SQL.

    if current_user.identity.nil?
      redirect_to root_url, notice: 'Access Denied! Business1766'

    elsif current_user.level > 19 && current_user.identity.id == @business.identity_id
      @business = Business.find(params[:id])

      #if level is big enough, one can only see herself or himself
    else
      redirect_to root_url, notice: 'Access Denied! Business34275'
    end
  end

  # GET /businesses/new
  def new

    if current_user.level < 20
      redirect_to root_url, notice: 'Access Denied! Business675'
    else

      @business = Business.new
    end
  end

  # GET /businesses/1/edit
  def edit
    if current_user.level > 19 && current_user.identity.id == @business.identity_id
      @business = Business.find(params[:id])

      #if level is big enough, one can only see herself or himself
    else
      redirect_to root_url, notice: 'Access Denied! Business34275'
    end
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:identity_id, :name, :pinyin, :btype, :website, :contact, :telephone, :account, :codeword, :note)
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_form.html.erb
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :identity %>
    <%= f.input :name %>
    <%= f.input :pinyin %>
    <%= f.input :btype %>
    <%= f.input :website %>
    <%= f.input :contact %>
    <%= f.input :telephone %>
    <%= f.input :account %>
    <%= f.input :codeword %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">修改关联企业Edit Business</div>
  <div id="index-card">
    <div><%= @business.identity.chinese_name %></div>
    <div><%= @business.name %></div>

    <div><%= @business.btype %></div>
    <div><%= @business.website %></div>
  </div>
<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :contact %>
    <%= f.input :telephone %>
    <%= f.input :account %>
    <%= f.input :codeword %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<p>&nbsp;</p>


</div>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/businesses/index.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">关联企业Businesses</div>


<p>&nbsp;</p>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Identity</th>
      <th>Name</th>

      <th>Btype</th>
      <th>Website</th>



      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @businesses.each do |business| %>
      <tr>
        <td><%= business.identity.chinese_name %></td>
        <td>
          <% if current_user.level > 19 && current_user.identity.id == business.identity_id %>
            <div id="bold"><%= link_to business.name, business %></div>
          <% else %>
            <%= business.name %>
          <% end %>
        </td>

        <td><%= business.btype %></td>
        <td><%= business.website %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.level > 19 %>
  <div class="bottom-menu">
    <table id="full">
      <tr>
        <td width = "20%">
        </td>

        <td width = "20%">
        </td>

        <td width = "20">
            <%= link_to image_tag('icons/handshake-plus-filled.png', width: '35', height: '35', title: '设立项目', rel: 'tooltip'), new_business_path %><div id="menu-font">添加企业</div>
        </td>

        <td width = "20%">
        </td>

        <td width = "20%">
        </td>
      </tr>
    </table>
  </div>
<% end %>

</div>

app/views/businesses/new.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%"></td>

      <td width = "20%"></td>
    </tr>

  </table>
</div>

<p></p>

<div id="page-title">创建新的关联企业New Business</div>

<%= simple_form_for(@business) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :identity_id, :value => current_user.identity.id %>

    <%= f.input :name, label: false, placeholder: "Business Name企业名称，必填。" %>
    <%= f.input :pinyin, label: false, placeholder: "English Name英文名称或拼音，必填。" %>
    <%= f.input :btype, label: false, placeholder: "Business Type企业类别，必填。" %>
    <%= f.input :website, label: false, placeholder: "Website URL企业网站地址，必填。" %>
    <p></p>
    <p>以上信息可以被其他同事看见。以下信息仅自己可见．</p>
    <p></p>
    <%= f.input :contact, label: false, placeholder: "Contact Name联系人名字，必填。" %>
    <%= f.input :telephone, label: false, placeholder: "Telephone Number电话号码，必填。" %>
    <%= f.input :account, label: false, placeholder: "Account Number账号号码，必填。" %>
    <%= f.input :codeword, label: false, placeholder: "Password账号密码，必填。" %>
    <%= f.input :note, label: false, placeholder: "Details详细描述，必填。" %>
  </div>

  <%= f.button :button do %>
    Submit提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "Submit提交!" %>
  <% end %>
<% end %>

<p>&nbsp;</p>

<div id="index-card">

  <h3>常见问题回答：</h3>
  <p>
    问：发现填写数据错误，可以删除吗？</br>
    答：在１小时之内，可以自由删除并且重新填写。
  </p>
  <p>
    问：所有的信息都会被其他同事看见吗？</br>
    答：第一个部分的信息可以被其他同事看见。第二个部分的信息仅自己可见．
  </p>

  <p></p>
</div>

</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/businesses/show.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), expenses_path %><div id="menu-font">返回支出</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%"></td>

      <td width = "20%"><%= link_to image_tag('icons/expense-filled.png', width: '30', height: '30', title: '费用报账', rel: 'tooltip'), expenses_path %></td>
    </tr>

  </table>
</div>

<p></p>

<div id="page-title">关联企业Business</div>

<div id="index-card">
  <p>
    <strong>Identity:</strong>
    <%= @business.identity.chinese_name %>, <%= @business.identity.user.email %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @business.name %>
  </p>

  <p>
    <strong>Pinyin:</strong>
    <%= @business.pinyin %>
  </p>

  <p>
    <strong>Btype:</strong>
    <%= @business.btype %>
  </p>

  <p>
    <strong>Website:</strong>
    <%= @business.website %>
  </p>

  <p>&nbsp;</p>

  <p>
    <strong>Contact:</strong>
    <%= @business.contact %>
  </p>

  <p>
    <strong>Telephone:</strong>
    <%= @business.telephone %>
  </p>

  <p>
    <strong>Account:</strong>
    <%= @business.account %>
  </p>

  <p>
    <strong>Codeword:</strong>
    <%= @business.codeword %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= @business.note %>
  </p>
</div>

<p>&nbsp;</p>

<div id="index-card">

  <h3>常见问题回答：</h3>
  <p>
    问：发现填写数据错误，可以删除吗？</br>
    答：在１小时之内，可以自由删除并且重新填写。
  </p>
  <p>
    问：所有的信息都能够修改吗？</br>
    答：第二个部分的信息可以被修改。
  </p>

  <p></p>
</div>

<div class="bottom-menu">
  <table id="full">
    <tr>
      <td width = "20%">
      </td>

      <td width = "20%">
      </td>

      <td width = "20">

            <div class="btn-group dropup">
              <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div><%= image_tag('icons/plus-filled.png', width: '35', height: '35', title: '更多菜单', rel: 'tooltip') %></div>

              </button>

              <div class="dropdown-menu">
                <div>
                  <%= link_to image_tag('icons/handshake-filled.png', width: '25', height: '25', title: '返回', rel: 'tooltip'), businesses_path %> <%= link_to 'All Businesses全部企业', businesses_path %>
                </div>
                <div>
                  <% if current_user.level > 19 && current_user.identity.id == @business.identity_id %><%= link_to image_tag('icons/forward-arrow-filled.png', width: '25', height: '25', title: '修改企业', rel: 'tooltip'), edit_business_path(@business) %> <%= link_to 'Edit business修改企业', edit_business_path(@business) %><% end %>
                </div>
                <div>
                  <% if current_user.identity.id == @business.identity_id && Time.zone.now - @business.created_at < 3600 %><%= link_to image_tag('icons/trash-filled.png', width: '25', height: '25', title: '删除', rel: 'tooltip'), @business, method: :delete, data: { confirm: 'Are you sure to delete确定删除吗?' } %> <%= link_to 'Delete删除企业?', @business, method: :delete, data: { confirm: 'Are you sure to delete确定删除吗?' } %><% end %></td>
                  <!--1 is ONE second. 60*60 = 3600s/h, thus 3600 is ONE hour. Please change to how many days later a user can delete his identity before having a residence in production-->

                </div>

                <div>

                </div>

                <div>


                </div>

              </div>
            </div>
      </td>

      <td width = "20%"></td>

      <td width = "20%"></td>
    </tr>

  </table>
</div>

</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>