config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :backgrounds
  resources :references
  resources :interviews
  resources :assessments
  resources :participants
  resources :projects
  resources :expenses
  resources :businesses
  resources :resumes

  resources :contributions do
    member do
      get 'index_individual'
    end
  end

  resources :offers

  resources :identities

  get 'home/dsds'
  get 'home/news'
  get 'home/about'
  get 'home/help'
  get 'home/letter'
  get 'home/letter_short'
  root 'home#index'

  devise_for :users

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, :except => [:letter_short, :help, :news]
    #password protected static pages. except...
    
  def index
  end

  def letter_short
  end

  def help
  end

  def letter
  end

  def news
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/help.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%"></td>

      <td width = "20%"></td>
    </tr>

  </table>
</div>

<div>
  If you have trouble for login or register, please contact 15002338190@139.com
</div>
</div>

app/views/home/index.html.erb
<div class="content-box">

  <div id="page-title">Home家园，一个温馨的地方</div>
<p></p>

<div id="index-card">
  <div>

    <% if current_user.identity.nil? %>
    <div>
      请填写个人信息 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '30', height: '30', title: '个人信息', rel: 'tooltip'), :controller=>"identities", :action=>"new", :id=>current_user.id %>
    </div>
      <% else %>

      <div>
        请查看个人信息 <%= link_to image_tag('icons/ID-one-filled.png', width: '30', height: '30', title: '个人信息', rel: 'tooltip'), :controller=>"identities", :action=>"show", :id=>current_user.identity.id %>
      </div>
      <p></p>
        <% if current_user.identity.resume.nil? %>
          <div>
            请上传自己的简历 <%= link_to image_tag('icons/forward-arrow-filled.png', width: '30', height: '30', title: '个人信息', rel: 'tooltip'), :controller=>"resumes", :action=>"new", :id=>current_user.identity.id %>
          </div>
        <% else %>
          <div>
            请查看自己的简历 <%= link_to image_tag('icons/resume-one-filled.png', width: '30', height: '30', title: '个人信息', rel: 'tooltip'), :controller=>"resumes", :action=>"show", :id=>current_user.identity.resume.id %>
          </div>


      <p>&nbsp;</p>
      <div>
        <%= image_tag('haimati-200.png', width: '35', height: '35', title: '肖像', class: "img-circle") %> 公司创始人的公开信 <%= link_to image_tag('icons/letter-filled.png', width: '25', height: '25', title: '公开信'), 'home/letter' %>
      </div>

        <p></p>
          <% if current_user.level > 19 %>
            <div class="bottom-menu">
              <table id="full">
                <tr>
                  <td width = "20%">
                  </td>

                  <td width = "20%">
                  </td>

                  <td width = "20">

                        <div class="btn-group dropup">
                          <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <div><%= image_tag('icons/logo.png', width: '35', height: '35', title: '更多菜单', rel: 'tooltip') %></div>

                          </button>

                          <div class="dropdown-menu">
                            <div>
                              <%#= link_to image_tag('icons/forum-filled.png', width: '32', height: '32', title: '小区论坛', rel: 'tooltip'), forums_path %> <%#= link_to "录取工资", :controller=>"offers", :action=>"show", :id=>current_user.identity.offer.id %>
                            </div>
                            <div>
                              <!--
                              <% if current_user.identity.contributions.empty? %>
                                <%= link_to image_tag('icons/contribution-plus-filled.png', width: '30', height: '30', title: '股权贡献', rel: 'tooltip'), :controller=>"contributions", :action=>"new", :id=>current_user.identity.id %> <%= link_to "添加贡献", :controller=>"contributions", :action=>"new", :id=>current_user.identity.id %>
                              <% else %>
                                <%= link_to image_tag('icons/contribution-filled.png', width: '30', height: '30', title: '股权贡献', rel: 'tooltip'), contributions_path %> <%= link_to "股权贡献", contributions_path %>
                              <% end %>
                            -->
                              <%= link_to image_tag('icons/contribution-filled.png', width: '30', height: '30', title: '股权贡献', rel: 'tooltip'), contributions_path %> <%= link_to "股权贡献", contributions_path %>
                            </div>

                            <div>
                              <%= link_to image_tag('icons/expense-filled.png', width: '30', height: '30', title: '费用报账', rel: 'tooltip'), expenses_path %> <%= link_to "费用报账", expenses_path %>
                            </div>
                            <div>
                              <%= link_to image_tag('icons/project-filled.png', width: '30', height: '30', title: '项目管理', rel: 'tooltip'), projects_path %> <%= link_to "项目管理", projects_path %>
                            </div>

                            <div>
                              <%= link_to image_tag('icons/ID-filled.png', width: '30', height: '30', title: '合伙同事', rel: 'tooltip'), identities_path %> <%= link_to "合伙同事", identities_path %>
                            </div>
                          </div>
                        </div>

                  </td>

                  <td width = "20%"></td>

                  <td width = "20%" id="image-holder"></td>
                </tr>

              </table>
            </div>

          <% end %><!--if current_user.level > 19 ends-->

      <% end %>

  <% end %>
</div>



</div><!--content-box ends-->

  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>

  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>

app/views/home/letter_short.html.erb
<div id="index-card">
  <h3><%= image_tag('cartoon-portrait.jpeg', width: '35', height: '35', title: '返回', rel: 'tooltip') %> 给合伙人的公开信(简版)：</h3>

  <p id="main-content">1998年自从住房商品化改革以来，中国城市化进程的速度惊人．今天，业主们拥有私有住家单元面积的比例，纵观中国上下五千年的历史，恐怕也是史无前例的．
  </p>

  <p id="main-content">打破了地域限制的咱们，远离了自己老家独特而熟悉的风土人情，住进了一个陌生的新建小区里．咱们应该如何才能与同样来自于五湖四海的小区邻居们和谐共处呢？咱们和其他小区业主们应该如何协同合作，来主导小区的管理问题呢？如何处理好和小区物业管理公司之间的关系呢？ <<物业管理条例>>赋予了小区业主们有召开业主大会, 决定小区事务的权利, 但把一个小区里的成百上千的业主们集中在一个地点, 一个时间里开会, 这在现实中如何办到呢?
  </p>

  <p id="main-content">以上这几个问题每天都在困扰着小区里的业主和居民们，而且正在变得越来越尖锐和棘手．市场上的手机应用数量繁多, 竟然没有一款是从小区业主和居民们的视角, 来维护咱们小区家园的美好! 这正是创业者们的机会!
  </p>

  <p id="main-content">“朝天门信息技术公司”正是以生产解决以上这几个棘手问题的互联网工具－－“戴山人家”入手，最终打造一款定位于陌陌和微信之间的＂半熟人＂的交流, 交往和管理的社交手机应用．咱们的梦想是区区相连互助, 维护家园小区的美好!
  </p>

  <p id="main-content">如果咱们合伙人在一起足够地努力，运气也足够地好，“戴山人家”手机应用也许在3到7年之间，能够拥有1亿到3亿用户，可以使“朝天门信息技术公司”在纳斯达克上，拥有200亿到600亿人民币的市值．（请参照陌陌和微博的用户数和在纳斯达克上的市值.）
  </p>

  <p id="main-content">当然，千里之行始于足下，这一切都要起始于咱们应该如何创立这家公司上. “朝天门信息技术公司”是一家新颖的互联网公司，有"非常吓人"的动态股权分配方案，组织架构和工作形式．
  </p>

  <h3><%= image_tag('icons/sunflower.png', width: '25', height: '25', title: '返回') %> 首先，公司是一家由无数的合伙人自愿地，自由地组合而形成的．公司里没有传统意义上的老板，每一位合伙人都是公司的主人．</h3>
  <p></p>

  <p id="main-content">每一位合伙人可以用现金投资和劳务投资进入公司，由现金和劳务贡献的多寡来决定每一位合伙人的股权百分比. 股权百分比月月变动，是动态的，而非静态的，是公开的，而非封闭的，是透明的，而非隐藏的．这样，公司的合伙人不仅拥有主观能动性，而且工作人员数目灵活多变，团队工作能力不断地优化，几乎可以适应任何的疑难项目，可以对抗任何的融资周期和经济周期．
  </p>

  <h3><%= image_tag('icons/tulip.png', width: '25', height: '25', title: '返回') %> 第二，每位合伙人工作的地点和时间都不是固定的，而是移动的和弹性的．</h3>
  <p></p>

  <p id="main-content">每一位合伙人用自己的手机移动地办公，可以是在自己的家里，也可以是在附近的咖啡厅里, 又或者是在租赁的"共享办公室"里等等；您不必固定地早九晚五，只要弹性地每天工作8小时，每周40小时就好. 公司更看重工作和生活的平衡, 不会要求任何人加班．当然，您必须调动自己的主观能动性，自动自发地为咱们共同拥有的公司工作，否则其他合伙人会选择不再和您合伙，并且希望您还是选择一家，老板叫干啥就干啥，早九晚五的，每天拥挤在上下班道路上的传统公司比较适合您．
  </p>

  <h3><%= image_tag('icons/blue-flower.png', width: '25', height: '25', title: '返回') %> 第三，公司内部管理是公开的, 透明的, 而不像传统公司那样是封闭的, 隐藏的.</h3>
  <p></p>

  <p id="main-content">不仅仅动态股权分配方案是公开透明的，公司的财务状况也是公开透明的．管理层甚至会像上市公司一样，每三个月就给合伙人发布一次财务报告．每一位合伙人都会明白，什么时候应该放弃一部分的，甚至是全部的现金工资，让它们转化为股权，以便公司度过艰难的时期；什么时候公司的收入足以给每一位合伙人发放20%, 50%, 70%, 或者100%的现金工资；什么时候公司可以根据股权百分比，适当地让每一位合伙人分享利润红利了.
  </p>

  <h3><%= image_tag('icons/rose.png', width: '25', height: '25', title: '返回') %> 第四, 充分地激发每一位合伙人创造创新能力.</h3>
  <p></p>

  <p id="main-content">公司的第一个手机应用产品，定位在维护家园的美好和记录小区的历史, 以此来精制互联网应用工具，以方便小区业主和居民们行使对管理小区的主导权. 咱们不是一家物业管理公司, 甚至都不太像一家传统意义上的互联网社交媒体公司. 咱们也许是在创造一个全新的品类, 正在进入一个从没有人到过的陌生地域去开疆辟土，这不正是互联网创业激动人心的地方吗?
  </p>

  <p id="main-content">所以每一位合伙人必须深度地思考公司的业务, 在原有的工作上和项目上大胆创新试错, 甚至跨界发展. 管理层更看重每个项目完成以后的结果, 而非过程. 虽然在法律和道德上不能犯错, 但公司容许在工作上犯错, 因为越想创新, 就越有可能在工作中犯错, 这是可以理解和被原谅的.
  </p>

  <p id="main-content">以上的四点, 但您必须要实名登记了以后, 就可以读到非常详细的介绍.
  </p>

  <p id="main-content">笔者不才, 已经为公司设计好了3到7年的战略规划，期待和您这位合伙人一起来实现!
  </p>

  <p>
  </p>
  <p>海客加州
  </p>
  <p>2018.7.28
  </p>

  <p><a class="top-up" href="#top"><%= image_tag('icons/scroll-up.png', width: '25', height: '25', title: '上') %></a>
</div>


<p>&nbsp;</p>

<div id="index-card">
  <h3 id="合伙人简介">公司合伙人简介:</h3>

  <div id="instroduction">
    <table style="width:100%">

      <tr>
        <td style="width:50%"><%= image_tag('xiaoqu-portrait-left-100.png', width: '80', height: '80', title: '肖像', class: "img-circle", id: "right") %></td>
        <td id="introduction" style="width:50%">
          邓丹力（Denny Deng)</br>
          公司创始人</br>
          351906071@qq.com</br>
          15002338190</br>
        </td>

      </tr>
    </table>

  </div>

  <p></p>
  <div>

    <p id="partners">邓丹力设计和开发了“XXXXX”1.0版本和公司内部管理手机应用, 是主要架构师，程序员, 也兼职临时CEO的角色<p/>

    <p id="partners">出生于重庆，17岁时随父母移民美国，在加利福利亚州的高中学校读过高三。在90年代以经济管理学士学位，毕业于<a href="https://baike.baidu.com/item/%E5%8A%A0%E5%88%A9%E7%A6%8F%E5%B0%BC%E4%BA%9A%E5%A4%A7%E5%AD%A6%E6%88%B4%E7%BB%B4%E6%96%AF%E5%88%86%E6%A0%A1/6564147?fromtitle=%E5%8A%A0%E5%B7%9E%E5%A4%A7%E5%AD%A6%E6%88%B4%E7%BB%B4%E6%96%AF%E5%88%86%E6%A0%A1&fromid=5383260&fr=aladdin" target="_blank">加州大学，戴维斯校区．</a>　母校被誉为“公立常春藤”盟校，属于Tier-1(最高级别) 全美最顶尖公立大学之一。著名的经济学家，<a href="https://baike.baidu.com/item/%E8%AE%B8%E5%B0%8F%E5%B9%B4/7316764?fr=aladdin" target="_blank">许小年</a>是在母校获得的经济学博士学位．

    <p id="partners">在美国第三大手机通讯公司<a href="https://baike.baidu.com/item/Sprint/4705050" target="_blank">SPRINT</a>做过顾客服务，也批发销售过电脑零件。通过自学互联网开发技术后，帮助<a href="http://wiki.mbalib.com/wiki/%E7%BE%8E%E5%9B%BD%E6%9C%97%E8%AE%AF%E7%A7%91%E6%8A%80%E5%85%AC%E5%8F%B8" target="_blank">美国朗讯科技</a>，<a href="https://baike.baidu.com/item/%E6%83%A0%E6%99%AE/275141?fromtitle=%E6%83%A0%E6%99%AE%E5%85%AC%E5%8F%B8&fromid=2626554&fr=aladdin" target="_blank">惠普公司</a>, 深圳协众国际设计开发过网站，也帮助<a href="http://www.kguowai.com/html/9455.html" target="_blank">ZipRealty Inc.</a>买卖过房地产。在美国的创新中心，加利福利亚州的硅谷地区，总共有20多年的学习，生活，和工作经历。

    <p id="partners">虽然在中国只有一个工作经历，但以业主的身份长期居住生活在重庆也有9年之久，并旅行到过中国内地20多个城市和地区，包括北京，上海，深圳，广州等等，对中国社会的历史，民情，文化，和政治经济都非常熟悉了解。

    <p><a class="nav-link" href="#top"><%= image_tag('icons/scroll-up.png', width: '25', height: '25', title: '上') %></a>
  </div>
</div>
<p></p>
<p></p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/home/news.html.erb
news