config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :backgrounds
  resources :references
  resources :interviews
  resources :assessments
  resources :participants
  resources :projects
  resources :expenses
  resources :businesses
  resources :resumes

  resources :contributions do
    member do
      get 'index_individual'
    end
  end

  resources :offers

  resources :identities

  get 'home/dsds'
  get 'home/news'
  get 'home/about'
  get 'home/help'
  get 'home/letter'
  get 'home/letter_short'
  root 'home#index'

  devise_for :users

end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :identity

  validates :identity_id, presence: true, uniqueness: true

  validates :mobile_number, presence: true
  validates :payment_method, presence: true
  validates :payment_account, presence: true
  validates :emergency_contact, presence: true
  validates :relationship, presence: true

  validates :mobile, presence: true

  default_scope -> { order(created_at: :desc) }
  
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy]

  # GET /enrollments
  # GET /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1
  # GET /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments
  # POST /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully created.' }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1
  # PATCH/PUT /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1
  # DELETE /enrollments/1.json
  def destroy
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrollment_params
      params.require(:enrollment).permit(:identity_id, :mobile_number, :payment_method, :payment_account, :emergency_contact, :relationship, :mobile, :approved)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :identity %>
    <%= f.input :mobile_number %>
    <%= f.input :payment_method %>
    <%= f.input :payment_account %>
    <%= f.input :emergency_contact %>
    <%= f.input :relationship %>
    <%= f.input :mobile %>
    <%= f.input :approved %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/edit.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">Editing Enrollment验证入职信息</div>

  <div id="index-card">


    <div><%= @enrollment.identity.chinese_name %></div>
    <p>
      <strong>Mobile number:</strong>
      <%= @enrollment.mobile_number %>
    </p>

    <p>
      <strong>Payment method:</strong>
      <%= @enrollment.payment_method %>
    </p>

    <p>
      <strong>Payment account:</strong>
      <%= @enrollment.payment_account %>
    </p>

    <p>
      <strong>Emergency contact:</strong>
      <%= @enrollment.emergency_contact %>
    </p>

    <p>
      <strong>Relationship:</strong>
      <%= @enrollment.relationship %>
    </p>

    <p>
      <strong>Mobile:</strong>
      <%= @enrollment.mobile %>
    </p>
  </div>

<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.input :approved, label: "Approved验证通过。" %>
  </div>

  <%= f.button :button do %>
    Submit提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "Submit提交!" %>
  <% end %>
<% end %>

</div>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/enrollments/index.html.erb
<h1>Enrollments</h1>

<table>
  <thead>
    <tr>
      <th>Identity</th>
      <th>Mobile number</th>
      <th>Payment method</th>
      <th>Payment account</th>
      <th>Emergency contact</th>
      <th>Relationship</th>
      <th>Mobile</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td><%= enrollment.identity.chinese_name %></td>
        <td><%= enrollment.mobile_number %></td>
        <td><%= enrollment.payment_method %></td>
        <td><%= enrollment.payment_account %></td>
        <td><%= enrollment.emergency_contact %></td>
        <td><%= enrollment.relationship %></td>
        <td><%= enrollment.mobile %></td>
        <td><%= enrollment.approved %></td>
        <td><%= link_to 'Show', enrollment %></td>
        <td><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td><%= link_to 'Destroy', enrollment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrollment', new_enrollment_path %>

app/views/enrollments/new.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">New Enrollment入职信息</div>

<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :identity_id, :value => current_user.identity.id %>
    <%= f.input :mobile_number, label: false, placeholder: "Your mobile Number您的手机号码，必填。" %>
    <%= f.input :payment_method, label: false, placeholder: "Payment Method工资支付方法，必填。" %>
    <%= f.input :payment_account, label: false, placeholder: "Payment Account工资支付账号，必填。" %>
    <%= f.input :emergency_contact, label: false, placeholder: "Emergency Contact紧急联络人，必填。" %>
    <%= f.input :relationship, label: false, placeholder: "Relationship与她他的关系，必填。" %>
    <%= f.input :mobile, label: false, placeholder: "Her/His Mobile Number她他的手机号码，必填。" %>

  </div>

  <%= f.button :button do %>
    Submit提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "Submit提交!" %>
  <% end %>
<% end %>

</div>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/enrollments/show.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"><%= link_to image_tag('icons/resume-one-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), :controller => 'resumes', :action => 'show', :id => @enrollment.identity.resume.id %></td>
      </tr>

    </table>
  </div>

  <div id="page-title">入职信息</div>

  <div id="index-card">


<p>
  <strong>Identity:</strong>
  <%= @enrollment.identity.chinese_name %>
</p>

<p>
  <strong>Mobile number:</strong>
  <%= @enrollment.mobile_number %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @enrollment.payment_method %>
</p>

<p>
  <strong>Payment account:</strong>
  <%= @enrollment.payment_account %>
</p>

<p>
  <strong>Emergency contact:</strong>
  <%= @enrollment.emergency_contact %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @enrollment.relationship %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @enrollment.mobile %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @enrollment.approved %>
</p>

</div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>