config/routes.rb
Rails.application.routes.draw do
  resources :enrollments
  resources :backgrounds
  resources :references
  resources :interviews
  resources :assessments
  resources :participants
  resources :projects
  resources :expenses
  resources :businesses
  resources :resumes

  resources :contributions do
    member do
      get 'index_individual'
    end
  end

  resources :offers

  resources :identities

  get 'home/dsds'
  get 'home/news'
  get 'home/about'
  get 'home/help'
  get 'home/letter'
  get 'home/letter_short'
  root 'home#index'

  devise_for :users

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :identity
  belongs_to :user

  validates :user_id, presence: true
  validates :fullname, presence: true, length: { minimum: 2, maximum: 42 }
  validates :mobile, presence: true, length: { minimum: 2, maximum: 42 }
  validates :relationship, presence: true, length: { maximum: 42 }
  validates :company_name, presence: true, length: { maximum: 42 }
  validates :company_url, presence: true, length: { maximum: 42 }
  validates :position, presence: true, length: { maximum: 42 }

  default_scope -> { order(created_at: :desc) }
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  before_action :set_reference, only: [:show, :edit, :update, :destroy]

  # GET /references
  # GET /references.json
  def index
    @references = Reference.all
  end

  # GET /references/1
  # GET /references/1.json
  def show
  end

  # GET /references/new
  def new
    @reference = Reference.new
  end

  # GET /references/1/edit
  def edit
  end

  # POST /references
  # POST /references.json
  def create
    @reference = Reference.new(reference_params)

    respond_to do |format|
      if @reference.save
        format.html { redirect_to @reference, notice: 'Reference was successfully created.' }
        format.json { render :show, status: :created, location: @reference }
      else
        format.html { render :new }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /references/1
  # PATCH/PUT /references/1.json
  def update
    respond_to do |format|
      if @reference.update(reference_params)
        format.html { redirect_to @reference, notice: 'Reference was successfully updated.' }
        format.json { render :show, status: :ok, location: @reference }
      else
        format.html { render :edit }
        format.json { render json: @reference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /references/1
  # DELETE /references/1.json
  def destroy
    @reference.destroy
    respond_to do |format|
      format.html { redirect_to references_url, notice: 'Reference was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reference
      @reference = Reference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reference_params
      params.require(:reference).permit(:identity_id, :fullname, :mobile, :relationship, :company_name, :company_url, :position, :verified, :note, :user_id)
    end
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/views/references/_form.html.erb
<%= simple_form_for(@reference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :identity %>
    <%= f.input :fullname %>
    <%= f.input :mobile %>
    <%= f.input :relationship %>
    <%= f.input :company_name %>
    <%= f.input :company_url %>
    <%= f.input :position %>
    <%= f.input :verified %>
    <%= f.input :note %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/references/edit.html.erb
<div class="content-box">
  <div>
    <table id="full">
      <tr>
        <td width = "20%">
          <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
        </td>

        <td width = "20%">

        </td>

        <td width = "20">

        </td>

        <td width = "20%"></td>

        <td width = "20%"></td>
      </tr>

    </table>
  </div>

  <div id="page-title">Editing Reference验证介绍人</div>

  <div id="index-card">

    <p>
      <strong>Identity:</strong>
      <%= @reference.identity.chinese_name %>
    </p>

    <p>
      <strong>Fullname:</strong>
      <%= @reference.fullname %>
    </p>

    <p>
      <strong>Mobile:</strong>
      <%= @reference.mobile %>
    </p>

    <p>
      <strong>Relationship:</strong>
      <%= @reference.relationship %>
    </p>

    <p>
      <strong>Company name:</strong>
      <%= @reference.company_name %>
    </p>

    <p>
      <strong>Company url:</strong>
      <%= @reference.company_url %>
    </p>

    <p>
      <strong>Position:</strong>
      <%= @reference.position %>
    </p>
  </div>

<p>&nbsp;</p>

<div>
  <%= simple_form_for(@reference) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <%= f.input :verified, label: 'Verified Checked打勾验证' %>
      <%= f.input :note, label: false, placeholder: "Details详情，必填。" %>
      <%= f.hidden_field :user_id, :value => current_user.id %>

    </div>

    <%= f.button :button do %>
      Submit提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "Submit提交!" %>
    <% end %>
  <% end %>
</div>

</div>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/references/index.html.erb
<p id="notice"><%= notice %></p>

<h1>References</h1>

<table>
  <thead>
    <tr>
      <th>Identity</th>
      <th>Fullname</th>
      <th>Mobile</th>
      <th>Relationship</th>

      <th>Verified</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @references.each do |reference| %>
      <tr>
        <td><%= reference.identity.chinese_name %></td>
        <td><%= reference.fullname %></td>
        <td><%= reference.mobile %></td>
        <td><%= reference.relationship %></td>

        <td><%= reference.verified %></td>


        <td><%= link_to 'Show', reference %></td>
        <td><%= link_to 'Edit', edit_reference_path(reference) %></td>
        <td><%= link_to 'Destroy', reference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reference', new_reference_path %>

app/views/references/new.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%"></td>

      <td width = "20%"></td>
    </tr>

  </table>
</div>


<div id="page-title">New Reference介绍人</div>

<%= simple_form_for(@reference) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.hidden_field :identity_id, :value => params[:id] %>
    <%= f.input :fullname, label: false, placeholder: "Full Name全名，必填。" %>
    <%= f.input :mobile, label: false, placeholder: "Mobile Phone Number？手机号码，必填。" %>
    <%= f.input :relationship, label: false, placeholder: "Is she/he your她他是您的？，必填。" %>
    <%= f.input :company_name, label: false, placeholder: "Company Name公司名称，必填。" %>
    <%= f.input :company_url, label: false, placeholder: "Company URL公司网络地址，必填。" %>
    <%= f.input :position, label: false, placeholder: "Professional Position专业职位，必填。" %>

    <%= f.input :note %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <%= f.button :button do %>
    Submit提交！ <%= image_tag "icons/forward-arrow-filled.png", :size => '25x25', :title => "Submit提交!" %>
  <% end %>
<% end %>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

app/views/references/show.html.erb
<div class="content-box">

<div>
  <table id="full">
    <tr>
      <td width = "20%">
        <%= link_to image_tag('icons/back-arrow-filled.png', width: '30', height: '30', title: '返回', rel: 'tooltip'), 'javascript:history.back()' %><div id="menu-font">返回上页</div>
      </td>

      <td width = "20%">

      </td>

      <td width = "20">

      </td>

      <td width = "20%">
        <% if @reference.identity_id == current_user.identity.id && Time.zone.now - @reference.created_at < 3600 %>
          <%= link_to image_tag('icons/trash-filled.png', width: '25', height: '25', title: '删除', rel: 'tooltip'), @reference, method: :delete, data: { confirm: 'Delete确定删除？' } %>
        <% end %>
      </td>

      <td width = "20%"><%= link_to image_tag('icons/resume-one-filled.png', width: '25', height: '25', title: '返回', rel: 'tooltip'), :controller => 'resumes', :action => 'show', :id => @reference.identity.resume.id %></td>
    </tr>

  </table>
</div>


<div id="page-title">reference介绍人</div>
<p>&nbsp;</p>

<div id="index-card">
  <div>
    <%= time_ago_in_words(@reference.created_at) %>以前，
  </div>
<p></p>

<p>
  <strong>Identity:</strong>
  <%= @reference.identity.chinese_name %>
</p>

<p>
  <strong>Fullname:</strong>
  <%= @reference.fullname %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @reference.mobile %>
</p>

<p>
  <strong>Relationship:</strong>
  <%= @reference.relationship %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @reference.company_name %>
</p>

<p>
  <strong>Company url:</strong>
  <%= @reference.company_url %>
</p>

<p>
  <strong>Position:</strong>
  <%= @reference.position %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @reference.verified %>
</p>

<p>
  <strong>Note:</strong>
  <%= @reference.note %>
</p>

<p>&nbsp;</p>

<% if @reference.user.identity.id != @reference.identity_id && current_user.level > 79 %>
  <div>
    <h4>verified by </h4>
    <%= @reference.user.identity.chinese_name %>
  </div>
<% end %>
</div>
<p>&nbsp;</p>
</div>